JUPYTERHUB_DATA_PATH="./jupyterhub_data"
NOTEBOOK_DATA_PATH="./notebook_data"

DOCKER_UID=1001 DOCKER_GID=1001 DOCKER_USERNAME=wangjun \
INTERNAL_UID=1002 INTERNAL_GID=100 INTERNAL_USERNAME=deeplearning \
HOST=0.0.0.0 \
JUPYTERHUB_DATA_PATH="$JUPYTERHUB_DATA_PATH" \
NOTEBOOK_DATA_PATH="$NOTEBOOK_DATA_PATH" \
docker-compose build --no-cache --force-rm
